### ISSUE TITLE
cpu_runtime和cuda_runtime加载模型失败

### ISSUE THREAD

**Issue by Azyka** [InfiniTensor/InfiniTensor#184]
# 问题描述
在docker中按步骤完成InfiniTensor python安装后，使用cpu_runtime和cuda_runtime加载模型遇到报错：
- cpu_runtime
```
Stack trace (most recent call last):
#3    Object "/workspace/InfiniTensor/pyinfinitensor/src/pyinfinitensor/backend.cpython-310-x86_64-linux-gnu.so", at 0x7f0582707854, in 
#2    Source "/workspace/InfiniTensor/src/core/runtime.cc", line 22, in run
         19:     for (auto &op : graph->getOperators()) {
         20:         auto kernelAttrs =
         21:             KernelAttrs{device, op->getOpType().underlying(), op->getDType()};
      >  22:         Kernel *kernel = kernelRegistry.getKernel(kernelAttrs);
         23:         auto perfKey = PerfEngine::Key{kernelAttrs, op->getOpPerfKey()};
         24:         auto perfData = perfEngine.getPerfData(perfKey);
#1    Source "/workspace/InfiniTensor/include/core/kernel.h", line 105, in getKernel
        102:     }
        103:     Kernel *getKernel(const KernelAttrs &kernelAttrs) const {
        104:         auto it = kernels.find(kernelAttrs);
      > 105:         IT_ASSERT(it != kernels.end(),
        106:                   "Kernel not found for key {" +
        107:                       to_string(enum_to_underlying(std::get<0>(kernelAttrs))) +
        108:                       ", " + std::to_string(std::get<1>(kernelAttrs)) + ", " +
#0    Source "/workspace/InfiniTensor/src/utils/exception.cc", line 15, in Exception
         12: Exception::Exception(const std::string &msg)
         13:     : std::runtime_error(msg), info(msg) {
         14:     backward_trace::StackTrace st;
      >  15:     st.load_here(32);
         16:     backward_trace::Printer p;
         17:     p.print(st);
         18: }
Traceback (most recent call last):
  File "/workspace/modified_nnsmith/equality_saturation_helper/test.py", line 14, in <module>
    stub.run()
  File "/workspace/InfiniTensor/pyinfinitensor/src/pyinfinitensor/onnx.py", line 1119, in run
    self.handler.run()
RuntimeError: [/workspace/InfiniTensor/include/core/kernel.h:105] Assertion failed (it != kernels.end()): Kernel not found for key {1, 21, Float32}
```
- cuda_runtime
```
Stack trace (most recent call last):
#0    Source "/workspace/InfiniTensor/src/utils/exception.cc", line 15, in Exception
         12: Exception::Exception(const std::string &msg)
         13:     : std::runtime_error(msg), info(msg) {
         14:     backward_trace::StackTrace st;
      >  15:     st.load_here(32);
         16:     backward_trace::Printer p;
         17:     p.print(st);
         18: }
Traceback (most recent call last):
  File "/workspace/modified_nnsmith/equality_saturation_helper/test.py", line 6, in <module>
    stub = OnnxStub(onnx.load("0.onnx"), backend.cuda_runtime())
RuntimeError: [/workspace/InfiniTensor/include/cuda/cuda_runtime.h:48] CUDA error (cudaMalloc(&ptr, size)): out of memory
```

要加载模型很小，只有一个cast操作，正常不会有cuda内存问题（docker中安装的torch可以正常使用gpu），模型也可以用ORT运行。

# 模型
[model.zip](https://github.com/InfiniTensor/InfiniTensor/files/13449114/model.zip)

# 环境
- Intel CPU: 12700K
- NVIDIA GPU: RTX 1660
- NVIDIA Driver Version: 525.147.05
- CUDA Version: 12.0
- CUDNN Version: 8.9.6.50
- Operating System: Ubuntu 22.04.3 LTS (x86_64)
- Python Version: 3.10.12

**Comment by Azyka** [comment]
我换了设备仍然遇到相同的报错，应该不是设备问题。
新环境：
AMD CPU: AMD EPYC 7763 64-Core Processor
NVIDIA GPU: Tesla V100S-PCIE-32GB
NVIDIA Driver Version: 525.147.05
CUDA Version: 11.8
CUDNN Version: 8.9.6.50
Operating System: Ubuntu 22.04.3 LTS (x86_64)
Python Version: 3.10.12

- `cpu_runtime`
```
#2    Source "/workspace/InfiniTensor/src/core/runtime.cc", line 22, in run
         19:     for (auto &op : graph->getOperators()) {
         20:         auto kernelAttrs =
         21:             KernelAttrs{device, op->getOpType().underlying(), op->getDType()};
      >  22:         Kernel *kernel = kernelRegistry.getKernel(kernelAttrs);
         23:         auto perfKey = PerfEngine::Key{kernelAttrs, op->getOpPerfKey()};
         24:         auto perfData = perfEngine.getPerfData(perfKey);
#1    Source "/workspace/InfiniTensor/include/core/kernel.h", line 105, in getKernel
        102:     }
        103:     Kernel *getKernel(const KernelAttrs &kernelAttrs) const {
        104:         auto it = kernels.find(kernelAttrs);
      > 105:         IT_ASSERT(it != kernels.end(),
        106:                   "Kernel not found for key {" +
        107:                       to_string(enum_to_underlying(std::get<0>(kernelAttrs))) +
        108:                       ", " + std::to_string(std::get<1>(kernelAttrs)) + ", " +
#0    Source "/workspace/InfiniTensor/src/utils/exception.cc", line 15, in Exception
         12: Exception::Exception(const std::string &msg)
         13:     : std::runtime_error(msg), info(msg) {
         14:     backward_trace::StackTrace st;
      >  15:     st.load_here(32);
         16:     backward_trace::Printer p;
         17:     p.print(st);
         18: }
Traceback (most recent call last):
  File "/workspace/modified_nnsmith/equality_saturation_helper/test.py", line 26, in <module>
    model.run()
  File "/workspace/InfiniTensor/pyinfinitensor/src/pyinfinitensor/onnx.py", line 1162, in run
    self.handler.run()
RuntimeError: [/workspace/InfiniTensor/include/core/kernel.h:105] Assertion failed (it != kernels.end()): Kernel not found for key {1, 21, Float32}
```
- `cuda_runtime`
```
#3    Source "/workspace/InfiniTensor/src/cuda/cuda_runtime.cc", line 87, in run
         84:     if (runTune)
         85:         tune(graph, profiling);
         86:     else
      >  87:         runWithoutSync(graph);
         88:     sync();
         89: }
#2    Source "/workspace/InfiniTensor/src/cuda/cuda_runtime.cc", line 30, in runWithoutSync
         27:         // HACK: set correct data type
         28:         auto kernelAttrs =
         29:             KernelAttrs{device, op->getOpType().underlying(), op->getDType()};
      >  30:         Kernel *kernel = kernelRegistry.getKernel(kernelAttrs);
         31:         auto perfKey = PerfEngine::Key{kernelAttrs, op->getOpPerfKey()};
         32:         auto perfData = perfEngine.getPerfData(perfKey);
         33:         // IT_ASSERT(perfData, "No perf data for OP " + op->toString());
#1    Source "/workspace/InfiniTensor/include/core/kernel.h", line 105, in getKernel
        102:     }
        103:     Kernel *getKernel(const KernelAttrs &kernelAttrs) const {
        104:         auto it = kernels.find(kernelAttrs);
      > 105:         IT_ASSERT(it != kernels.end(),
        106:                   "Kernel not found for key {" +
        107:                       to_string(enum_to_underlying(std::get<0>(kernelAttrs))) +
        108:                       ", " + std::to_string(std::get<1>(kernelAttrs)) + ", " +
#0    Source "/workspace/InfiniTensor/src/utils/exception.cc", line 15, in Exception
         12: Exception::Exception(const std::string &msg)
         13:     : std::runtime_error(msg), info(msg) {
         14:     backward_trace::StackTrace st;
      >  15:     st.load_here(32);
         16:     backward_trace::Printer p;
         17:     p.print(st);
         18: }
Traceback (most recent call last):
  File "/workspace/modified_nnsmith/equality_saturation_helper/test.py", line 13, in <module>
    stub.run()
  File "/workspace/InfiniTensor/pyinfinitensor/src/pyinfinitensor/onnx.py", line 1162, in run
    self.handler.run()
RuntimeError: [/workspace/InfiniTensor/include/core/kernel.h:105] Assertion failed (it != kernels.end()): Kernel not found for key {2, 21, Float32}
```

**Comment by whjthu** [comment]
您好，上面的错误是由两个原因造成：一是我们框架对于数据类型转换算子（cast）的支持还不齐全，我们会在近期进行补齐；二是我们框架本身有个内存池机制，其中会预留 7GB 作为 workspace 给算子库使用，所以在游戏卡上会爆内存，我们调整下内存池策略修复一下这个问题。

**Comment by Azyka** [comment]
> 您好，上面的错误是由两个原因造成：一是我们框架对于数据类型转换算子（cast）的支持还不齐全，我们会在近期进行补齐；二是我们框架本身有个内存池机制，其中会预留 7GB 作为 workspace 给算子库使用，所以在游戏卡上会爆内存，我们调整下内存池策略修复一下这个问题。

感谢您的回复，但我第二次复现使用了32G显存的v100，且在运行examples中的resnet_inference.py时遇到了相同的问题。
```
#2    Source "/workspace/InfiniTensor/src/core/runtime.cc", line 22, in run
         19:     for (auto &op : graph->getOperators()) {
         20:         auto kernelAttrs =
         21:             KernelAttrs{device, op->getOpType().underlying(), op->getDType()};
      >  22:         Kernel *kernel = kernelRegistry.getKernel(kernelAttrs);
         23:         auto perfKey = PerfEngine::Key{kernelAttrs, op->getOpPerfKey()};
         24:         auto perfData = perfEngine.getPerfData(perfKey);
#1    Source "/workspace/InfiniTensor/include/core/kernel.h", line 105, in getKernel
        102:     }
        103:     Kernel *getKernel(const KernelAttrs &kernelAttrs) const {
        104:         auto it = kernels.find(kernelAttrs);
      > 105:         IT_ASSERT(it != kernels.end(),
        106:                   "Kernel not found for key {" +
        107:                       to_string(enum_to_underlying(std::get<0>(kernelAttrs))) +
        108:                       ", " + std::to_string(std::get<1>(kernelAttrs)) + ", " +
#0    Source "/workspace/InfiniTensor/src/utils/exception.cc", line 15, in Exception
         12: Exception::Exception(const std::string &msg)
         13:     : std::runtime_error(msg), info(msg) {
         14:     backward_trace::StackTrace st;
      >  15:     st.load_here(32);
         16:     backward_trace::Printer p;
         17:     p.print(st);
         18: }
Traceback (most recent call last):
  File "/workspace/InfiniTensor/examples/python/resnet_inference.py", line 19, in <module>
    model.run()
  File "/workspace/InfiniTensor/pyinfinitensor/src/pyinfinitensor/onnx.py", line 1119, in run
    self.handler.run()
RuntimeError: [/workspace/InfiniTensor/include/core/kernel.h:105] Assertion failed (it != kernels.end()): Kernel not found for key {1, 137, Float32}
```

**Comment by whjthu** [comment]
对，这个也是卡在了 cast kernel 的问题上。目前 cast kernel 在 cpu 和 gpu 的支持都有问题，我们争取下周能把相关支持完善一下。

**Comment by Azyka** [comment]
谢谢，我尝试了一些其他算子，发现可以正常运行
